-- 코드를 입력하세요
SELECT DISTINCT A.CART_ID AS CART_ID
FROM (
    SELECT CART_ID, NAME 
    FROM CART_PRODUCTS 
    WHERE NAME IN ('Milk', 'Yogurt')
    ) B
JOIN CART_PRODUCTS A ON B.CART_ID = A.CART_ID
WHERE (A.NAME = 'Milk' AND B.NAME = 'Yogurt')
OR (A.NAME = 'Yogurt' AND B.NAME = 'Milk')
ORDER BY A.CART_ID