-- 코드를 입력하세요 
SELECT D.ANIMAL_ID, D.NAME FROM 
    (SELECT A.ANIMAL_ID, MAX(A.DATETIME - B.DATETIME) AS MAX_TIME 
    FROM ANIMAL_OUTS A 
        JOIN ANIMAL_INS B 
        ON A.ANIMAL_ID = B.ANIMAL_ID
    GROUP BY A.ANIMAL_ID
    ORDER BY MAX_TIME DESC
    ) C
JOIN ANIMAL_OUTS D ON C.ANIMAL_ID = D.ANIMAL_ID
WHERE ROWNUM <= 2;