-- 코드를 입력하세요
SELECT B.FOOD_TYPE, B.REST_ID, REST_NAME, B.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES 
        FROM REST_INFO
        GROUP BY FOOD_TYPE
     ) A
JOIN REST_INFO B 
    ON A.FOOD_TYPE = B.FOOD_TYPE 
    AND MAX_FAVORITES = B.FAVORITES
ORDER BY A.FOOD_TYPE DESC;