-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, 
    CITY 
    || ' ' || STREET_ADDRESS1 
    || ' ' || STREET_ADDRESS2 AS 전체주소,
    SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4) 
    AS 전화번호
FROM USED_GOODS_USER A 
JOIN USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
GROUP BY USER_ID, NICKNAME, CITY 
    || ' ' || STREET_ADDRESS1 
    || ' ' || STREET_ADDRESS2, 
    SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4) 
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC;