-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE INSTR(SEX_UPON_INTAKE, 'Intact') > 0
) A
JOIN (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE('Spayed%')
    OR SEX_UPON_OUTCOME LIKE('Neutered%')
) B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY A.ANIMAL_ID;