-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, PRICE * SUM_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN 
    (SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT -- 식품별 총 주문량
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') LIKE '2022-05' -- 2022년 5월의
    GROUP BY PRODUCT_ID) B -- 식품별
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;