-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A 
JOIN PATIENT B ON A.PT_NO = B.PT_NO
JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE APNT_CNCL_YN = 'N' AND TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
ORDER BY APNT_YMD;