-- 코드를 입력하세요
WITH HOURS AS (
    SELECT LEVEL - 1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24
)

SELECT B.HOUR AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS B
LEFT JOIN ANIMAL_OUTS A 
ON B.HOUR = TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
GROUP BY B.HOUR
ORDER BY B.HOUR;