-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD')
FROM 
    (SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT -- 회원 별 리뷰 작성 수
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    FETCH FIRST 1 ROW ONLY -- 리뷰 작성 수가 가장 많은 회원 ID 1개 조회
    ) A
JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
JOIN REST_REVIEW C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;