-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, 
    A.CAR_ID, COUNT(*) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN ( -- 특정 기간(시작일 기준) 동안, 자동차 별 대여횟수가 5회 이상인 ID만 조회
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE -- 시작일이
       BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') 
       AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
    GROUP BY CAR_ID -- 자동차 ID별
    HAVING COUNT(*) >= 5
    ) B -- 대여횟수 5회 이상
ON A.CAR_ID = B.CAR_ID
WHERE START_DATE -- 시작일이
    BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') 
    AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), A.CAR_ID
ORDER BY MONTH, A.CAR_ID DESC;