-- 코드를 작성해주세요
SELECT YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS B
JOIN ECOLI_DATA A
ON YEAR(A.DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR, YEAR_DEV;