-- 코드를 입력하세요
SELECT '/home/grep/src/' || A.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH 
FROM USED_GOODS_FILE B 
JOIN USED_GOODS_BOARD A ON B.BOARD_ID = A.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;