-- 코드를 입력하세요
SELECT B.CATEGORY, B.PRICE, B.PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY) A
JOIN FOOD_PRODUCT B ON A.CATEGORY = B.CATEGORY 
    AND MAX_PRICE = B.PRICE
WHERE B.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY B.PRICE DESC;