-- 코드를 작성해주세요
WITH
FE AS (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'),
CS AS (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'),
PY AS (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')

SELECT
    CASE 
        WHEN SKILL_CODE & (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 
            AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') = (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') = (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
        WHEN SKILL_CODE & (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 THEN 'C'
        ELSE NULL
    END
    AS GRADE, ID, EMAIL
FROM DEVELOPERS
WHERE (SKILL_CODE & (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 
       AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') = (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) 
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') = (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
    OR SKILL_CODE & (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
ORDER BY GRADE, ID;